apiVersion: v1
kind: Service
metadata:
  name: twiddits-ms
spec:
  selector:
    app: twiddits-ms
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
status:
  loadBalancer: {}